### PR TITLE
created the migrations for our staffs

### PR DESCRIPTION
**Pull request by nelliejellie**
I created a dbcontext for the staff application and configured the appsetting.json and startup.cs

### CODE REVIEW

**Comment by isaacRaphael** [comment]
Alright great

**Review by Nwachukwu-Uzor — APPROVED** [review]
Looks good to me

**Review by IfunanyaWilliam — APPROVED** [review]
Good to go.

**Review by isaacRaphael — APPROVED** [review]
Looks good

**Pull request merged**
